version: 3

project:
  locator: SolaceLabs_solace-tryme-cli-mcp-server
  id: SolaceLabs_solace-tryme-cli-mcp-server
  name: solace-tryme-cli-mcp-server
  teams: []
  labels:
    - javascript

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
